### ISSUE TITLE
Update Cheekaaboo.com Newsletter Signup Popup

### ISSUE THREAD

**Issue by AmyCKB** [benjamin8888/ckb#22]
ASAP:

Here's the link to retrieve the visual:
https://drive.google.com/drive/folders/0BwnLn_ABxC8AOE5OdHNGakRURW8?usp=sharing

**Comment by benjamin8888** [comment]
Similar to the previous news letter banner, you must remove the text filed and the button from the image.

**Comment by AmyCKB** [comment]
Hi Ben, if you look closely in the folder there are 2 images for you, one with text and the other without.

**Comment by benjamin8888** [comment]
And if you read my comment with more attention, you will notice that i am asking to REMOVE the button and text filed completely.(Removing the text is not enough)

**Comment by AmyCKB** [comment]
Updated.
