### ISSUE TITLE
Provide Access for Google Analytics

### ISSUE THREAD

**Issue by Baofoo** [benjamin8888/ckb#27]
Transfer it to cheekaaboo.active@gmail.com

**Comment by benjamin8888** [comment]
We will get this done during our monthly meeting at the end of the month to avoid possible loss of analytics data.

**Comment by benjamin8888** [comment]
Please provide the Google Analytic Account number for cheekaaboo.active@gmail.com in order to be able to use this new account to track the data.
You can read this official link by google on how to get the account number from your account:
https://support.google.com/analytics/answer/1008080?hl=en

**Comment by benjamin8888** [comment]
Done. Please check you Analytic account for future traffic observation.
