### ISSUE TITLE
Cheekaaboo.com.sg (Update)

### ISSUE THREAD

**Issue by AmyCKB** [benjamin8888/ckb#33]
- Menu Image Banner
- Newsletter signup pop-up banner

**Comment by benjamin8888** [comment]
Done. Please check. 
For SG Store, Let me know If you wish to have 6 menu option instead of 4. Give me the name of the 2 options.

**Comment by AmyCKB** [comment]
Hi Ben, 
We just need one more - "Rewards". Joeey will set the tab for you today. You may proceed on your part from where she have started. Thanks ~
