### ISSUE TITLE
Sg Website

### ISSUE THREAD

**Issue by AmyCKB** [benjamin8888/ckb#34]
1. Populate Customer Service link ( I have made a new set of copy for Singapore exchange policy - check your mail)
2. Arrange the menu tabs equally
3. Fix the Return/Exchange form interface
4. Please help to remove the store locator

**Comment by AmyCKB** [comment]
2. Hi Ben, we are not left to settle with the existing four tabs only, there is no longer rewards. Please try to make it look good with 4 tabs.

**Comment by benjamin8888** [comment]
Customer service link is Done.
Return and exchange interface is done.
Store locator is removed.

There isn't much that can be done for the menu.

I have created another task for shipment tracking for SG store as it requires separate implementation.
