### ISSUE TITLE
Amendment on Singapore website

### ISSUE THREAD

**Issue by AmyCKB** [benjamin8888/ckb#41]
1. "Affiliate" from footer
2. "Blog" from header
3. Please align the text properly on the contact us page. The text seems to be off.
4. Activate Testimonial page
5. What is the status on Singapore after Sales Review Newsletter?

**Comment by benjamin8888** [comment]
1- Done
2- need some more time. (changing header is complicated)
3- need some more time. 
4- Testimonial is deactivated due to the issue it was causing. I will remove the link from the page.
5- This is a separated feature. we need to plan this separately

**Comment by benjamin8888** [comment]
2- is removed from header.
4. Is removed from header.
3- is still work in progress.

**Comment by benjamin8888** [comment]
I have already applied the changes in contact us page.
Please check https://cheekaaboo.com/my/contacts  and verify changes.

**Comment by AmyCKB** [comment]
Hi Ben,

Thanks for this, one more thing please bring the co number to the second line instead as now its broken.

 

Cheers!
