### ISSUE TITLE
Trade in Program: Copy Change

### ISSUE THREAD

**Issue by AmyCKB** [benjamin8888/ckb#44]
Hi Ben please assist in the following "non - discounted swimsuit items" change to "non-sale Thermal Swimsuits and Floats."

@ this link: https://cheekaaboo.com/my/trade-in-program

**Comment by AmyCKB** [comment]
@benjamin8888 , please help to execute this a.s.a.p, thanks as we dont want any more misunderstanding from our client on our t&c.

**Comment by benjamin8888** [comment]
Done
