### ISSUE TITLE
Drop Review Automation Email

### ISSUE THREAD

**Issue by AmyCKB** [benjamin8888/ckb#48]
1. Please enlarge the font size
2. Can we customise this newsletter? If so please provide dimension.

**Comment by benjamin8888** [comment]
You can do customization  on the design of the email by opening MailChimp and going to "Campaigns" tab. then open any review automation for any specific product that you wish to edit.
P.S: All the review campaign names starts with "Review - " 
Example : "Review - warmiebabes-suit"

**Comment by AmyCKB** [comment]
Noted, thanks.
